### PR TITLE
Push Drush Command

### PR DESCRIPTION
**Pull request by gido**

### CODE REVIEW

**Review by WengerK — APPROVED** [review]

**Comment by WengerK** [comment]
- I think we should still add the last push on state. (with his own service & tests)
- Also, what about using the configured path file ? Should we add another feature to use the Drupal Cron ?

**Comment by gido** [comment]
>     * I think we should still add the last push on state. (with his own service & tests)

Agree 👍 

>     * Also, what about using the configured path file ? Should we add another feature to use the Drupal Cron ?

I'm not convinced about the feature to manually push .po file into Loco with an UI. I don't understand who will use this and in which case. Same for the configuration about push automation via cron.

For me, this must stay a manual operation by a developer who know what it is doing and a drush command is enough and easy to maintain.

**Comment by gido** [comment]
@tonifisler I'm interested to ear your view about this

**Comment by tonifisler** [comment]
That's exactly my point in #4 😉 Push command should stay CLI-only.

**Pull request merged**
